# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Dev:
      runs-on: ubuntu-latest
      environment: Prod
      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        - name: Checkout
          id: checkout
          uses: actions/checkout@v4

        - name: Test Local Action
          id: test-action
          uses: ./
          with:
            milliseconds: 1000

        - name: Print Output
          id: output
          run: echo "${{ steps.test-action.outputs.time }}"
  Prod:
      runs-on: ubuntu-latest
      environment: Prod
      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        - name: Checkout
          id: checkout
          uses: actions/checkout@v4

        - name: Test Local Action
          id: test-action
          uses: ./
          with:
            milliseconds: 1000

        - name: Print Output
          id: output
          run: echo "${{ steps.test-action.outputs.time }}"
